spring:
  application:
    name: personal-finance-tracker
  datasource:
    url: jdbc:postgresql://localhost:5432/budgetbuddy
    driver-class-name: org.postgresql.Driver
    username: haroon
    password: "@Haru0821@"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    # Add these for better JPA configuration
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
server:
  port: 8080
logging:
  level:
    # Fixed package name to match your actual package
    com.budgetbuddy.personal_finance_tracker: DEBUG
    org.springframework.security: DEBUG
    org.springframework.data.jpa: DEBUG
    org.hibernate: DEBUG
    org.hibernate.orm.deprecation: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.orm.jpa: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

app:
  jwt:
    # IMPORTANT: Generate a stronger secret key (at least 256 bits)
    secret: myverysecuresuperlongjwtsecretkeythatisatleast256bitslong123456789
    expiration: 86400000 # 24 hours in milliseconds